/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { CategoryRequest } from './models/category-request';
export { CategoryResponse } from './models/category-response';
export { PageResponseCategoryResponse } from './models/page-response-category-response';
export { PageResponseProductResponse } from './models/page-response-product-response';
export { ProductRequest } from './models/product-request';
export { ProductResponse } from './models/product-response';
export { UpdateCategoryRequest } from './models/update-category-request';
export { UpdateProductRequest } from './models/update-product-request';
